# Generated by Django 4.0.5 on 2023-02-08 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('villa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repverificationmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repverificationmessage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villa.unit'),
        ),
        migrations.AddField(
            model_name='interimsettlementmessage',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.building'),
        ),
        migrations.AddField(
            model_name='interimsettlementmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interimsettlementmessage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.unit'),
        ),
        migrations.AddField(
            model_name='interimsettlementmessage',
            name='villa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.villa'),
        ),
        migrations.AddField(
            model_name='billmessage',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.building'),
        ),
        migrations.AddField(
            model_name='billmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billmessage',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.unit'),
        ),
        migrations.AddField(
            model_name='billmessage',
            name='villa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='villa.villa'),
        ),
        migrations.AddField(
            model_name='announcementmessage',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcementmessage',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villa.unit'),
        ),
    ]
