version: "3.9"

services:
  django:
    container_name: django_service
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=main
      - POSTGRES_USER=blocket
      - POSTGRES_PASSWORD=Blocket1!!
      - POSTGRES_HOST=wooridong-rep.cyxls0c2nd3p.ap-northeast-2.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - BASE_URL=api.wooridong-rep.net
      - PROTOCOL=https

