from .register_view import register_view
from .check_identification_duplicate import check_identification_duplicate_view
from .get_user_view import get_user_view
from .logout_view import LogoutView
from .delete_user_view import delete_user_view
from .change_password_view import change_password_view
from .check_phone_number_view import check_phone_number_view
