# Generated by Django 4.0.5 on 2023-02-08 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadAddr', models.CharField(max_length=255)),
                ('roadAddrPart1', models.CharField(blank=True, max_length=255, null=True)),
                ('roadAddrPart2', models.CharField(blank=True, max_length=255, null=True)),
                ('jibunAddr', models.CharField(blank=True, max_length=255, null=True)),
                ('engAddr', models.CharField(blank=True, max_length=255, null=True)),
                ('zipNo', models.CharField(blank=True, max_length=5, null=True)),
                ('admCd', models.CharField(blank=True, max_length=15, null=True)),
                ('rnMgtSn', models.CharField(blank=True, max_length=15, null=True)),
                ('bdNm', models.CharField(blank=True, max_length=255, null=True)),
                ('udrtYn', models.CharField(blank=True, max_length=1, null=True)),
                ('buldMnnm', models.IntegerField(blank=True, null=True)),
                ('buldSlno', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('account_owner', models.CharField(blank=True, default='account_owner_not_set', max_length=50, null=True)),
                ('building_count', models.IntegerField(default=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='villa.address')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepTakeOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('is_takeover', models.BooleanField(default=False)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villa_list', to='villa.villa')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.IntegerField(default=0)),
                ('building_name', models.CharField(blank=True, max_length=10, null=True)),
                ('has_elevator', models.BooleanField(default=False)),
                ('floors', models.IntegerField(default=5)),
                ('lines', models.IntegerField(default=2)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='villa.villa')),
            ],
            options={
                'unique_together': {('villa', 'building_number')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('person_count', models.IntegerField(blank=True, default=0, null=True)),
                ('floor', models.IntegerField(default=99)),
                ('line', models.IntegerField(default=99)),
                ('does_exist', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='villa.building')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_unit', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='villa.villa')),
            ],
            options={
                'unique_together': {('villa', 'building', 'unit_number')},
            },
        ),
    ]
