# Generated by Django 4.0.5 on 2023-02-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='owner',
        ),
    ]
