# Generated by Django 4.0.5 on 2023-02-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0002_remove_unit_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villa',
            old_name='created',
            new_name='date_created',
        ),
    ]
