# Generated by Django 4.0.5 on 2023-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villa', '0003_rename_created_villa_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='date_created',
            field=models.DateField(),
        ),
    ]
