from .villa_serializer import VillaSerializer
from .villa_create_serializer import VillaCreateSerializer
from .building_serializer import BuildingSerializer
from .building_create_serializer import BuildingCreateSerializer
from .unit_serializer import UnitSerializer
from .unit_with_bill_serializer import UnitWithBillSerializer
from .villa_update_serializer import VillaUpdateSerializer
from .villa_no_depth_serializer import VillaNoDepthSerializer
from .web_detail_unit_serializer import WebUnitDetailSerializer

