# Generated by Django 4.0.5 on 2023-02-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField()),
                ('due_date', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImposeFeeOnUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_impose', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImposeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterimSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('fees', models.JSONField(blank=True)),
                ('total_fee', models.IntegerField(blank=True)),
                ('target_date', models.DateTimeField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, default=1.05)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentUnitBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('total_fee', models.IntegerField(default=0)),
                ('person_count', models.IntegerField(default=0, null=True)),
                ('phone_number', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SentUnitFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentVillaFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(blank=True, default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('imposing_unit_count', models.IntegerField(blank=True, default=0)),
                ('imposing_person_count', models.IntegerField(blank=True, default=0)),
                ('individual', models.BooleanField(blank=True, default=False)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('interim_settlement_date', models.DateField(blank=True, null=True)),
                ('total_fee', models.IntegerField(default=0)),
                ('person_count', models.IntegerField(default=0, null=True)),
                ('phone_number', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UnitFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('is_individual', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VillaFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(blank=True, default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('imposing_unit_count', models.IntegerField(blank=True, default=0)),
                ('imposing_person_count', models.IntegerField(blank=True, default=0)),
                ('fixed', models.BooleanField(blank=True, default=False)),
                ('individual', models.BooleanField(blank=True, default=False)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bank')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villa_fee', to='fee.feetype')),
                ('impose_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fee.imposetype')),
            ],
        ),
    ]
