# Generated by Django 4.0.5 on 2023-02-10 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitfee',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='unitbill',
            name='date',
        ),
        migrations.RemoveField(
            model_name='unitfee',
            name='pay_date',
        ),
        migrations.RemoveField(
            model_name='villafee',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='villafee',
            name='pay_date',
        ),
        migrations.AddField(
            model_name='unitbill',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
