# Generated by Django 4.0.5 on 2023-02-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0005_alter_unitbill_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitbill',
            name='interim_settlement_date',
        ),
        migrations.RemoveField(
            model_name='unitbill',
            name='paid_date',
        ),
        migrations.AlterField(
            model_name='unitbill',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
