# Generated by Django 4.0.5 on 2023-04-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0007_alter_unitbill_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitbill',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
